name: simpleranks
version: '${project.version}'
main: simpleranks.Simpleranks
api-version: '1.20'

commands:
  simpleranks:
    description: Mit diesem Command kannst du dein komplettes Plugin managen!
    aliases:
      - sr

permissions:
  simpleranks.config:
    default: op
  simpleranks.rank.get:
    default: op
  simpleranks.rank.set:
    default: op