name: SimpleRanks
version: '${project.version}'
main: simpleranks.Simpleranks
api-version: '1.20'
authors:
  - Silal

commands:
  simpleranks:
    description: Mit diesem Command kannst du dein komplettes Plugin managen!
    aliases:
      - sr
  rank:
    description: Mit diesem Command kannst du den Rang eines Spielers aktualisieren/abrufen!

permissions:
  simpleranks.config:
    default: op
  simpleranks.playerrank.get:
    default: op
  simpleranks.playerrank.set:
    default: op
  simpleranks.playerrank.set.all:
    default: op
  simpleranks.rank.create:
    default: op
  simpleranks.rank.delete:
    default: op
  simpleranks.rank.list:
    default: op
  simpleranks.rank.modify:
    default: op
  simpleranks.rank.info:
    default: op